### ISSUE TITLE
Flutter 2 migration

### ISSUE THREAD

**Issue by pkozlovskiy** [QuantumArt/flutter_mobx_form_validation_kit#1]
Do you planinig migrate to flutter 2

**Comment by RussianDragon** [comment]
Hello. 
No, I have not check on Flutter 2 yet. 
But, if mobx is working on v2. I will switch project on Flutter 2 soon.

**Comment by RussianDragon** [comment]
> 
> 
> Do you planinig migrate to flutter 2

I was check flutter 2, and... mobx not stable on flutter 2

I don't undestend why no "XXX2"...
![image](https://user-images.githubusercontent.com/12259067/113518903-cf8f3e80-9591-11eb-8ac4-77989707add4.png)

Also i found problem in mobx_codegen...
I going write issues in mobx repository...

**Comment by RussianDragon** [comment]
> 
> 
> Do you planinig migrate to flutter 2

Updated to Flutter 2
https://pub.dev/packages/flutter_mobx_form_validation_kit

Thanks for using library
